/*
 * Copyright(c) 2019 Nippon Telegraph and Telephone Corporation
 */

package msf.ecmm.devctrl;

import java.util.ArrayList;
import java.util.List;

import msf.ecmm.common.CommandExecutor;
import msf.ecmm.common.CommonDefinitions;
import msf.ecmm.common.CommonUtil;
import msf.ecmm.common.LogFormatter;
import msf.ecmm.common.log.MsfLogger;

/**
 * Class for executing the script to upgrade OS in the device.
 */
public class NodeOsUpgradeScriptExecutor {

  /**
   * Logger.
   */
  private final MsfLogger logger = new MsfLogger();

  /** 
   * The SSH login to the executing node has failed.
   * （The return code generated by the sh script is defined).
   */
  private static final int SSH_LOGIN_NG = 255;

  /**
   * The OS image file is transffered and OS upgrade is executed. 
   *
   * @param scriptName
   *          The script file name (an absolute path)
   * @param ipaddr
   *           IF address for the device management
   * @param userId
   *           User ID to login to the node
   * @param password
   *           User Password for login to the node
   * @throws DevctrlException
   *           The execution failed.
   */
  public void executeNodeOsUpgradeScript(String scriptName, String ipaddr, String userId, String password)
      throws DevctrlException {
    logger.trace(CommonDefinitions.START);
    logger.debug("scriptName=" + scriptName + " ipaddr=" + ipaddr + " userId=" + userId + " password=" + password);

    List<String> stdList = new ArrayList<String>();
    List<String> errList = new ArrayList<String>();

    String[] params = { "bash", scriptName, ipaddr, userId, password };

    int ret = CommandExecutor.exec(params, stdList, errList);
    if (ret != 0) {
      if (ret == SSH_LOGIN_NG) {
        logger.warn(LogFormatter.out.format(LogFormatter.MSG_405097, ipaddr));
      }
      if (!CommonUtil.isFile(scriptName)) {
        logger.debug("Script file not found.");
      }
      logger.error(LogFormatter.out.format(LogFormatter.MSG_505096, scriptName));
      throw new DevctrlException("Script execution failure.");
    }
    logger.trace(CommonDefinitions.END);
  }

}
